Updated version wwfirstboot
git-svn-id: https://warewulf.lbl.gov/svn/trunk@1243 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/cluster/etc/wwfirstboot b/cluster/etc/wwfirstboot
--- a/cluster/etc/wwfirstboot
+++ b/cluster/etc/wwfirstboot
@@ -75,7 +75,7 @@
 # Start Warewulf Firstboot
 #
 # chkconfig: 2345 05 05
-# description: Start the Warewulf Firstboot Disk Check
+# description: Start the Warewulf Firstboot Checks
 #
 #
 ### BEGIN INIT INFO
@@ -84,334 +84,173 @@
 # Required-Stop:
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
-# Short-Description: start the first boot disk check
-# Description: Start the Warewulf firstboot disk check
+# Short-Description: Start the firstboot checks
+# Description: Start the Warewulf firstboot checks
 ### END INIT INFO
 
 #
-# wwfirstboot is a replacement for filesystem provisioning on the
-# compute nodes. It replaces the FILESYSTEM variable that is
-# normally used to, to make it possible to selectivly format
-# partitions (besides swap space), between reboots so we have 
-# persistant storage on nodes that lasts between reboots, yet the
-# node configuration does not need to be changed.
+# wwfirstboot is a mechinism to run commands on a node when they
+# first start. This includes disk partitioning/formating for
+# persistant storage, etc...
 #
+
 if [ ! -z $DEBUGWW ]; then
     set -x;
 fi
 
 . /etc/init.d/functions
 
+SUBSYSFILE="/var/lock/subsys/wwfirstboot";
 CONFIG="/etc/sysconfig/wwfirstboot.conf";
+
+wwfbdir="/usr/libexec/warewulf/wwfirstboot";
+
+# What "run" are we doing.
+# PRIMARY   == Initial call from chkconfig setup, starting at S05
+# SECONDARY == Ran from /etc/rc.d/rc.local as the very last thing
+#   when the system boots. Primary *should* be the default.
+RUN="PRIMARY";
+
+if [[ ! -d `dirname $SUBSYSFILE` ]]; then
+    # This should *never* happen ... but if for some reason it
+    # makes it here and /var/lock/subsys does *not* exist...
+    mkdir -p `dirname $SUBSYSFILE`;
+fi
+
+if [[ ! -f $SUBSYSFILE ]]; then
+    touch $SUBSYSFILE;
+fi
 
 if [ ! -f $CONFIG ]; then
     echo "No Firstboot configuration found. Skipping";
+    logger wwfirstboot ": WARNING - No Firstboot configuration found. Skipping";
     exit 0;
 fi
 
 . $CONFIG
 
+if [ ! -d $wwfbdir ]; then
+    msg_red "ERROR: Cannot find $wwfbdir";
+    failure; echo;
+    logger wwfirstboot ": ERROR - Cannot find $wwfbdir";
+    return 1;
+fi
+
+
 start()
 {
-    msg_blue "Starting wwfirstboot configuration:\n";
+    echo "RUNNING" > $SUBSYSFILE;
+    if [ ! -z $1 ]; then
+        RUN=$(echo $1 | tr '[a-z]' '[A-Z]');
+    fi
+
+    # Check to see if status passed is either 'PRIMARY' or 'SECONDARY'
+    if [[ "x${RUN}" != "xPRIMARY" && "x${RUN}" != "xSECONDARY" ]]; then
+        msg_status;
+        msg_red "ERROR: Unknown status $RUN:";
+        failure; echo
+        logger wwfirstboot ": ERROR - Unknown status $RUN";
+        return 1;
+    fi
+
+    msg_blue "Starting wwfirstboot $RUN configuration:\n";
 
     if [[ -z ${SKIP} || "x${SKIP}" == "xtrue" ]]; then
         msg_status;
         msg_red "SKIP Undefinded or set to true:";
         warning; echo;
+        logger wwfirstboot ": SKIP Undefined or set to true";
         return 0;
     fi
 
-    if [[ -z ${DISK} ]]; then
-        msg_status;
-        msg_red "DISK to configure undefined:";
-        failure; echo;
-        return 1;
-    fi
+    # See if we have any files that are to run secondary
+    if grep -q -li "^#STATUS: SECONDARY" $wwfbdir/*.wwfb; then
+        # Check if we've already modified rc.local
+        if ! egrep -q '^## WWFIRSTBOOT' /etc/rc.d/rc.local; then
+            cat >> /etc/rc.d/rc.local <<-EOF
 
-    if ! echo $DISK | egrep ^/ >/dev/null; then
-        DISK=/dev/$DISK;
-    fi
+## WWFIRSTBOOT secondary execution
+/etc/init.d/wwfirstboot start secondary
 
-    # Check for md# device .... Exit if we're give one
-    if echo $DISK | egrep -q '^/dev/md[0-9]*'; then
-        msg_status;
-        msg_red "DISK set as software raid device... ($DISK)";
-        failure; echo;
-        return 1;
-    fi
-
-    if [[ ! -b ${DISK} ]]; then 
-        msg_status;
-        msg_red "${DISK} does not appear to be a block special device.";
-        failure; echo;
-        return 1;
-    fi
-
-    msg_status;
-    msg_yellow "Configuring $DISK\n"
-
-    SIZE=`fdisk -l $DISK | grep "Disk $DISK" | awk '{print $5}'`
-    UNIT=`fdisk -l $DISK | grep ^Unit | awk '{print $9}'`
-
-    msg_status;
-    msg_yellow "DISK SIZE - $SIZE bytes ($(($SIZE/1024/1024/1024))GB)\n"
-
-    #XXX: We use $(( )) instead of piping through 'bc' just incase bc isn't 
-    #  installed
-    CYLINDERS=$(($SIZE/255/63/512))
-
-    msg_status;
-    msg_yellow "CYLINDERS - $CYLINDERS\n";
-
-    sfdisk_script=`mktemp`;
-    disk_fstab="/tmp/disk.fstab";
-    disk_fs="/tmp/disk.fs";
-
-    > $sfdisk_script;
-    > $disk_fstab;
-    > $disk_fs;
-
-    sfdisk -d $DISK > /tmp/${DISK##/dev/}_sfdisk.dump
-
-    if [ $? -ne 0 ]; then
-        msg_status;
-        msg_red "Disk dump of $DISK failed. Exiting....";
-        failure; echo;
-        logger -t wwfirstboot "Error: sfdisk dump of $DISK filed";
-        return 1;
-    fi
-
-    msg_status;
-    msg_yellow "WARNING -- Clearing partition table\n";
-    dd if=/dev/zero of=${DISK} bs=512 count=1 &>/dev/null;
-
-    vartmp=`mktemp`;
-
-    # Don't put this in the for loop command. Subshells opening messing things up
-    # when trying to pass values back and forth. -jms
-    set | egrep ^PART_ | sort > $vartmp;
-
-    for v in `cat $vartmp`; do
-        var=$(echo $v|cut -f1 -d '=');
-        val=$(echo $v|cut -f2 -d '=');
-        cyl="";
-        ptype="L";
-
-        #XXX: The values for this while loop are being redirected below from the
-        # ending done. This is to work around bash opening a subshell, and then
-        # not being able to break out of the loops. -jms
-        while read size type mp perms; do
-            test -z $size && break;
-
-            if [ "x${size}" == "xfill" ]; then
-                cyl='';
-            else
-                cyl=$(($size*1024*1024/$UNIT));
-                cyl=$(($cyl+1)); # Increment to be sure we cover the space
-            fi
-
-            if [ "x${type}" == "xswap" ]; then
-                ptype="S";
-            fi
-            
-            # Our Partition number is the '#' part of the PART_# variables
-            PARTNUM=`echo $var | cut -f 2 -d '_'`;
-
-            if [[ ${PARTNUM} -gt 4 ]]; then
-                msg_status;
-                msg_red "Warning: Ignoring PART_${PARTNUM}. Will only do 4 primary partitions.\n";
-                continue;
-            fi
-            echo ",${cyl},${ptype}" >> $sfdisk_script;
-
-
-            if [ "x${type}" == "xswap" ]; then
-                echo -e "${DISK}${PARTNUM}\tswap\tswap\tdefaults\t0 0" >> $disk_fstab;
-            else
-                echo -e "${DISK}${PARTNUM}\t${mp}\t${type}\tdefaults\t0 0" >> $disk_fstab;
-            fi
-            echo "${size}:${type}:${mp:-none}:${perms:-none}:${PARTNUM}" >> ${disk_fs};
-
-            if [ ! -d ${mp} ]; then
-                msg_blue "  Creating Mountpoint: ${mp}\n";
-                echo -n "  "; msg_status;
-                msg_white "mkdir -m ${perms} -p ${mp}\n";
-                mkdir -m ${perms} -p ${mp};
-
-                echo -n "  "; msg_status;
-                msg_white "chmod ${perms} ${mp}\n";
-                chmod ${perms} ${mp}
-            fi
-
-            # If we're going to fill the disk then we need to stop processing things,
-            # and continue on our way.
-            if [ "x${size}" == "xfill" ]; then
-                msg_status;
-                msg_yellow "Partition found with 'fill' size. Skipping any other partition defines.\n";
-                break 2;
-            fi
-        done< <(echo $val | tr ':' ' ')  # while read
-    
-    done  # for v
-
-    # Lets actually partition the disk. Keep a backup of the table "Just Incase". Won't
-    # help any if we format though.
-    cat $sfdisk_script | sfdisk -O /tmp/${DISK##/dev/}_runtime.save -H 255 -S 63 -C $CYLINDERS $DISK &> /dev/null
-
-    if [ ! -f /etc/fstab.wwfb_orig ]; then
-        cp -a /etc/fstab /etc/fstab.wwfb_orig;
-        chmod 600 /etc/fstab.wwfb_orig;
-    fi
-
-    # If we happen to be stateful, get rid of the old /etc/fstab before generating the
-    # new one. Won't matter much on a hybrid setup as root will be in RAM.
-    FSTAB=`mktemp`;
-    awk '/^#### Added in by wwfirstboot ####/ { exit; } { print; }' /etc/fstab > $FSTAB
-    cp $FSTAB /etc/fstab;
-    /bin/rm -f $FSTAB;
-
-    echo "#### Added in by wwfirstboot ####" >> /etc/fstab;
-    echo "#### Generated: $(date --utc) " >> /etc/fstab;
-    cat $disk_fstab >> /etc/fstab;
-
-    cat ${disk_fs} | tr ':' ' ' | while read size type mp perms pnum; do
-        # Always format swap space...
-        if [ "x${type}" == "xswap" ]; then
-            logger -t wwfirstboot "SWAP Space found. Formatting and running swapon for ${DISK}${pnum}";
-            msg_status;
-            msg_green "SWAP Space found. Formatting and running swapon for ${DISK}${pnum}\n";
-            swapoff ${DISK}${pnum} &>/dev/null; sleep 1;
-            mkswap ${DISK}${pnum} &>/dev/null; sleep 1;
-            swapon ${DISK}${pnum} &>/dev/null; sleep 1;
-            continue;
+EOF
         fi
+    fi
 
-        # Be sure our partition isn't mounted
-        umount ${DISK}${pnum} &>/dev/null;
-        if [[ ! -z ${FORMAT} && "x${FORMAT}" != "xnever" ]]; then
+    wwfb_files=$(LC_COLLATE=C grep -li "^#STATUS: $RUN" $wwfbdir/*.wwfb | sort | uniq);
+    WAS_ERROR=0;
+    for file in $wwfb_files; do
+        # If file isn't executable, continue
+        [ ! -x $file ] && continue;
 
-            # Always Format?
-            if [ "x${FORMAT}" == "xalways" ]; then
-                logger -t wwfirstboot "WARNING: Format set to always... We're formatting the partition."
-                msg_status;
-                msg_red "FORMAT set to always in config file.\n";
-                msg_status;
-                msg_red "Destroying data on ${DISK}${pnum} ....    ";
+        name=$(basename $file .wwfb);
+        echo "RUNNING: $name" > $SUBSYSFILE;
+        msg_status;
+        msg_green "Running $name:\n";
 
-                mkfs.${type} -q ${DISK}${pnum};
-                mount ${mp};
+        #TODO: Change files so they're executed instead of sourced.
+        #env /bin/sh $file;
+        source $file;
+        RETVAL=$?;
 
-                if [ $? -ne 0 ]; then
-                    logger -t wwfirstboot "ERROR: Could not mount ${DISK}${pnum} after formatting."
-                    echo "  "; msg_status;
-                    msg_red "ERROR: Could not mount ${DISK}${pnum} after formatting."
-                    failure; echo
-                    return 1;
-                fi
-
-                # Create the timestamp file
-                date +%s > ${mp}/.wwfirstboot_timestamp;
-                chmod 600 ${mp}/.wwfirstboot_timestamp;
-
-                continue;
-            fi
-
-            # Test mounting our partition
-            if ! mount -t ${type} ${DISK}${pnum} ${mp} 2>/dev/null 1>/dev/null; then
-                # Unable to mount. Assume it isn't formatted
-                msg_status;
-                msg_yellow "Formatting Partition number ${pnum} as ${type}";
-                warning; echo;
-                sleep 1;
-                mkfs.${type} -q ${DISK}${pnum};
-                mount ${mp};
-
-                if [ $? -ne 0 ]; then
-                    logger -t wwfirstboot "ERROR: Could not mount ${DISK}${pnum} after formatting."
-                    echo -n "  "; msg_status;
-                    msg_red "ERROR: Could not mount ${DISK}${pnum} after formatting."
-                    failure; echo
-                    return 1;
-                fi
-
-                # Create the timestamp file
-                date +%s > ${mp}/.wwfirstboot_timestamp;
-                chmod 600 ${mp}/.wwfirstboot_timestamp;
-
-            elif [ "x$FORMAT" == "xfirst" ]; then
-                # We, supposedly, mounted the partition. Lets see if our statefile exists, and
-                # if it doesn't: unmount, format, re-mount.
-                msg_status;
-                msg_red "Format on first boot only\n";
-                echo -n "    ";
-                msg_yellow "- Looking for existance of: ${mp}/.wwfirstboot_timestamp\n";
-
-                if [ ! -f ${mp}/.wwfirstboot_timestamp ]; then
-                    logger -t wwfirstboot "${mp}/.wwfirstboot_timestamp not found. Assuming we need to format.";
-                    echo -n "    "; msg_status;
-                    msg_red "${mp}/.wwfirstboot_timestamp *not* found...";
-                    warning; echo;
-                    umount ${mp};
-                    echo -n "    "; msg_status;
-                    msg_red "Formatting ..... ";
-                    mkfs.${type} -q ${DISK}${pnum};
-
-                    if ! mount ${mp} 2>/dev/null 1>/dev/null; then
-                        msg_status;
-                        msg_red "Mount of ${mp} Failed!"
-                        failure; echo;
-                        logger -t wwfirstboot "Error: Mount of ${mp} failed after format.";
-                        return 1;
-                    else
-                        # Create the timestamp file
-                        date +%s > ${mp}/.wwfirstboot_timestamp;
-                        chmod 600 ${mp}/.wwfirstboot_timestamp;
-
-                    fi
-                else
-                    echo -n "    "; msg_status;
-                    msg_green "${mp}/.wwfirstboot_timestamp was found.";
-                    success; echo;
-                fi
+        if [[ $RETVAL -eq 0 || $RETVAL -eq 1 ]]; then
+            if [ -n "$DEBUGWW" ]; then
+                echo "DEBUG: Return value of 0 or 1";
             fi
         else
-            msg_status;
-            msg_yellow "FORMAT not set, or set to never format. Drive setup may be\n";
-            msg_status;
-            msg_yellow "incomplete. Attemping mount of ${DISK}${pnum} to ${mp}.\n";
-            logger -t wwfirstboot "Warning: FORMAT not set, or set to never format. Drive setup may be incomplete.";
-            mount ${mp};
+            echo "Lethal error thrown by module: $name";
+            logger wwfirstboot "ERROR: Lethal error thrown by module: $name";
+            ERROR_NAME=$name;
+            WAS_ERROR=1;
+            break;
         fi
+    done
 
-        # Set perms again after mount for the new FS.
-        chmod ${perms} ${mp};
-    done;
+    if [ ${WAS_ERROR} -ne 0 ]; then
+        echo "ERROR: $ERROR_NAME" > $SUBSYSFILE;
+    else
+        echo "DONE" > $SUBSYSFILE;
+    fi
 
-    # Clean up
-    /bin/rm -f $sfdisk_script;
-    /bin/rm -f $disk_fstab;
-    /bin/rm -f $disk_fs;
-    /bin/rm -f $vartmp;
-
+    return $RETVAL;
 }
 
 stop()
 {
+    if [[ -f $SUBSYSFILE ]]; then
+        /bin/rm -f $SUBSYSFILE;
+    fi
     return 0;
+}
+
+status()
+{
+    RETVAL=0
+    echo -n "WWFIRSTBOOT STATUS: ";
+    if [[ -f $SUBSYSFILE ]]; then
+        cat $SUBSYSFILE;
+    else
+        echo "Unknown";
+        RETVAL=1;
+    fi
+
+    return $RETVAL;
 }
 
 ret=0;
 while [ "$#" -gt "0" ]; do
     case $1 in
     start)
-        start
+        shift;
+        start $@;
         ;;
     stop)
         stop
         ;;
+    status)
+        status
+        ;;
     *)
-        echo $"Usage: $0 {start|stop}"
+        echo $"Usage: $0 {start [secondary]|stop|status}"
         exit 4
     esac
     ret=$?
