Have wwgetfiles use a lockfile, so more than one cannot run at a time.
In case there's communication issues with the provisioner, more cron
jobs won't pile up


git-svn-id: https://warewulf.lbl.gov/svn/trunk@1822 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/provision/initramfs/capabilities/transport-http/wwgetfiles b/provision/initramfs/capabilities/transport-http/wwgetfiles
--- a/provision/initramfs/capabilities/transport-http/wwgetfiles
+++ b/provision/initramfs/capabilities/transport-http/wwgetfiles
@@ -11,6 +11,14 @@ if [ -n "$SET_X" ]; then
     set -x
 fi
 
+# Lock so more than one wwgetfiles cannot be ran
+if [ ! -f /tmp/.wwgetfiles.lock ]; then
+    touch /tmp/.wwgetfiles.lock
+else
+    echo "ERROR: wwgetfiles already running"
+    exit 1
+fi
+
 if [ -f /warewulf/transports/http/functions ]; then
     . /warewulf/transports/http/functions
 elif [ -f ./functions ]; then
@@ -105,4 +113,7 @@ while true; do
     echo -n "." 1>&2
     throttled_sleep
 done
+
+# Remove lock file
+rm -f /tmp/.wwgetfiles.lock
 
