Restructure of wwinit ICR module. Other minor updates.
git-svn-id: https://warewulf.lbl.gov/svn/trunk@1595 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/cluster/libexec/wwinit/50-nfsd.init b/cluster/libexec/wwinit/50-nfsd.init
--- a/cluster/libexec/wwinit/50-nfsd.init
+++ b/cluster/libexec/wwinit/50-nfsd.init
@@ -28,8 +28,9 @@ elif [ -x "/etc/rc.d/init.d/nfsd" ]; then
 elif [ -x "/etc/init.d/nfs-kernel-server" ]; then
     SERVICE_NAME="nfs-kernel-server"
 else
-    wwprint "Is NFS installed and loaded properly?" error
-    exit 255
+    wwprint " ! ERROR: NFS service not detected" error;
+    reply_error;
+    exit 255;
 fi
 
 
diff --git a/cluster/libexec/wwinit/50-ntpd.init b/cluster/libexec/wwinit/50-ntpd.init
--- a/cluster/libexec/wwinit/50-ntpd.init
+++ b/cluster/libexec/wwinit/50-ntpd.init
@@ -24,6 +24,10 @@ if [ -x "/etc/rc.d/init.d/ntpd" ]; then
     SERVICE_NAME="ntpd"
 elif [ -x "/etc/init.d/ntp" ]; then
     SERVICE_NAME="ntp"
+else
+    wwprint " ! ERROR: NTP client not found" error;
+    reply_error;
+    exit 255;
 fi
 
 
diff --git a/cluster/libexec/wwinit/50-tftp.init b/cluster/libexec/wwinit/50-tftp.init
--- a/cluster/libexec/wwinit/50-tftp.init
+++ b/cluster/libexec/wwinit/50-tftp.init
@@ -22,14 +22,18 @@ wwreqroot
 
 if [ -x "/etc/init.d/tftpd-hpa" ]; then
     SERVICE_NAME="tftpd-hpa"
-else
+elif [[ -x "/etc/rc.d/init.d/tftp" || -f "/etc/xinetd.d/tftp" ]]; then
     SERVICE_NAME="tftp"
+else
+    wwprint " ! ERROR: tftp client not found" error;
+    reply_error;
+    exit 1; 
 fi
 
-if [[ -z "$( which update-rc.d 2>/dev/null )" ]]; then
-    wwrun /sbin/chkconfig xinetd on || exit 1
-    wwrun /sbin/chkconfig $SERVICE_NAME on || exit 1
-    wwrun /sbin/service xinetd restart || exit 1
+if [[ -z "$( which update-rc.d  2>/dev/null)" ]]; then
+    wwrun /sbin/chkconfig xinetd on || exit 1;
+    wwrun /sbin/chkconfig $SERVICE_NAME on || exit 1;
+    wwrun /sbin/service xinetd restart || exit 1;
 else
     wwrun update-rc.d $SERVICE_NAME defaults 3 ;
     wwrun service $SERVICE_NAME restart || exit 1
diff --git a/cluster/libexec/wwinit/91-vnfs.init b/cluster/libexec/wwinit/91-vnfs.init
--- a/cluster/libexec/wwinit/91-vnfs.init
+++ b/cluster/libexec/wwinit/91-vnfs.init
@@ -73,7 +73,7 @@
 ##
 
 #INIT: ALL
-#INIT: ICR
+#INIT: VNFS
 
 if [ ! -f "$WWFUNCTIONS" ]; then
     wwprint "ERROR: Could not load Warewulf functions - $WWFUNCTIONS";
@@ -81,57 +81,39 @@ if [ ! -f "$WWFUNCTIONS" ]; then
 fi
 . ${WWFUNCTIONS};
 
-if [ ! -f "$WAREWULF_SYSCONFDIR/warewulf/wwinit/icr.functions" ]; then
-    wwprint "ERROR: Could not locate ICR wwinit functions!";
-    exit 255;
-fi
-. ${WAREWULF_SYSCONFDIR}/warewulf/wwinit/icr.functions;
-
 # Make sure we're the root user
 wwreqroot
 
-# Create basic chroot using the master node OS 
-wwprint "Creating base chroot\n";
-base_chroot;
-
-# Perform Intel(R) Cluster Ready specific configurations
-wwprint "Performing Intel(R) Cluster Ready specific configurations\n";
-icr_configs;
-
-# Install and configure Warewulf firstboot
-wwprint "Installing and configuring Warewulf Firstboot\n";
-wwfirstboot
-
-# Install Intel(R) Cluster Runtimes
-wwprint "Installing Intel(R) Cluster Runtimes\n";
-inst_icrt;
-
-# Install Intel(R) Cluster Checker
-wwprint "Installing Intel(R) Cluster Checker\n";
-inst_clck;
-
-# Install Intel(R) LAN drivers 
-wwprint "Installing and configuring Intel(R) LAN drivers\n";
-inst_iLAN_drivers; 
-
-# Call OFED build wwinit module 
-if [ -f "${WWINITDIR}/88-ofed.init" ]; then
-    sh ${WWINITDIR}/88-ofed.init;
-else
-    wwprint "ERROR: Could not locate OFED wwinit module!" error;
+# Check if a previous module created a chroot and defined its path.
+# If so, use it
+if [ -f  "${WWTMPDIR}/CHROOTDIR" ]; then
+   . ${WWTMPDIR}/CHROOTDIR; 
 fi
 
-# If the MIC module was requested, call it
-if [[ ! -z "$MIC_ENABLE" && "$MIC_ENABLE" -eq 1 ]];then
-    # Call MIC  wwinit module 
-    if [ -f "${WWINITDIR}/89-mic.init" ]; then
-        sh ${WWINITDIR}/89-mic.init;
-    else
-        wwprint "ERROR: Could not locate MIC wwinit module!" error;
+# In case CHROOTDIR was passed at execution time
+CHROOTDIR=${CHROOTDIR:-}
+
+# Some sanity checking
+if [[ -z "$CHROOTDIR" || ! -d "$CHROOTDIR" ]]; then
+    wwprint " ! ERROR: Invalid CHROOT path" error;
+    reply_error;
+    exit 255;
+fi
+
+if [ ! -f "${CHROOTDIR}/sbin/init" ]; then        
+    wwprint " ! ERROR: ${CHROOTDIR}/sbin/init not found,\n" error;
+    wwprint "         chroot may be corrupted" error;
+    reply_error;
+    exit 255;
+fi
+
+VNFS_NAME=$(basename ${CHROOTDIR});
+
+wwprint "Building the VNFS image and importing into Warewulf:\n"
+if wwrun wwvnfs -y --hybridpath=${CHROOTDIR} --chroot ${CHROOTDIR}; then
+    if [ -f "/etc/warewulf/defaults/provision.conf" ]; then
+        sed -i -e "s/^.*vnfs[ ]*=.*/vnfs = $VNFS_NAME/" /etc/warewulf/defaults/provision.conf;
     fi
+else 
+    exit 255;
 fi
-
-# Rebuild VNFS and the bootstrap with the installed stuff
-vnfs_boot_build
-
-# vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
