20-filesystems -- Adds in the ability to use 'fill' for a size. Be sure it's the *last* entry in the FILESYSTEMS variable, or it won't make you too happy. ;)
    80-mkbootable -- So, I ran into an issue with 'grub-install' (SL
6.3)... it just didn't work. *BUT* running the commands to setup grub
manually did work. So, this is a hack to work around that. If
grub-install fails, it generates a small set of commands, that is ran
in the chroot, which is used as input to grub to setup the boot loader
that way. Any output is sent to: /root/grubinstall.out  -- in
$NEWROOT.



git-svn-id: https://warewulf.lbl.gov/svn/trunk@1280 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/provision/initramfs/capabilities/setup-filesystems/80-mkbootable b/provision/initramfs/capabilities/setup-filesystems/80-mkbootable
--- a/provision/initramfs/capabilities/setup-filesystems/80-mkbootable
+++ b/provision/initramfs/capabilities/setup-filesystems/80-mkbootable
@@ -70,8 +70,28 @@ if [ -n "$WWBOOTLOADER" -a -f "/tmp/rootdev" ]; then
                     if chroot $NEWROOT /sbin/grub-install $WWBOOTLOADER >/dev/null; then
                         exit 0
                     else
-                        echo "Running grub-install failed!"
-                        exit 255
+                        gscript="/root/grubinstall.sh";
+                        grubscript=${NEWROOT}${gscript};
+                        grubtext=$NEWROOT/root/grubinstall.txt;
+
+                        echo -n "Running grub-install failed. Trying manually.";
+
+                        # Setup Commands to install GRUB
+                        echo "root (hd0,0)" > $grubtext;
+                        echo "setup (hd0)" >> $grubtext;
+                        echo "quit" >> $grubtext;
+
+                        # Bash script to run grub.
+                        echo "#!/bin/bash" > $grubscript;
+                        echo "/sbin/grub --batch < /root/grubinstall.txt &>/root/grubinstall.out" >> $grubscript;
+                        chmod 755 $grubscript;
+
+                        if chroot $NEWROOT $gscript &>/dev/null; then
+                            exit 0;
+                        else
+                            echo "Running grub-install failed!"
+                            exit 255
+                        fi
                     fi
                 else
                     echo "Could not find INITRD and/or KERNEL version!"
@@ -92,3 +112,6 @@ if [ -n "$WWBOOTLOADER" -a -f "/tmp/rootdev" ]; then
 else
     exit 1
 fi
+
+# vim: filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
+
