Extensive wwmkchroot rework .. minor.. testing successful with both centos-6.7 and debian-8.1
Goals:
    unify distro support
    between rpm and debs

    proper ISO support for debs

    standardize the overlay concept as a way of
    installing add-on packages into chroots

    provide dummy example options overlay

    remove context help section

    reduce word count by centralizing and
    removing redundant code

    general optimizations



git-svn-id: https://warewulf.lbl.gov/svn/trunk@1940 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/vnfs/bin/wwmkchroot.in b/vnfs/bin/wwmkchroot.in
--- a/vnfs/bin/wwmkchroot.in
+++ b/vnfs/bin/wwmkchroot.in
@@ -19,9 +19,7 @@ usage() {
     echo
     echo "OPTIONS:"
     echo "    -d        Debug output"
-    echo "    -h        Show usage or module specific help"
-    echo
-    echo
+    echo "    -h        Show usage"
     echo
     echo "TEMPLATE_NAME (select one of the following):"
     for i in $libexecdir/warewulf/wwmkchroot/*.tmpl; do
@@ -35,8 +33,8 @@ usage() {
     echo
     echo "EXAMPLES:"
     echo
-    echo " # wwmkchroot -h debian"
     echo " # wwmkchroot rhel-generic /var/chroots/rhel"
+    echo " # wwmkchroot debian8-64 /var/chroots/deb8"
     echo
 }
 
@@ -52,7 +50,8 @@ while getopts "a:dhv" opt; do
             VERBOSE=1
         ;;
         h)
-            SHOW_MODULE_HELP=1
+            usage
+            exit 0
         ;;
         a)
             var=$OPTARG
@@ -71,7 +70,6 @@ if [ -z "$VNFSTEMPLATE" ]; then
     usage
     exit 1
 fi
-
 
 #### Loading templates
 if [ -d "$libexecdir/warewulf/wwmkchroot" ]; then
@@ -97,22 +95,17 @@ else
     exit 1
 fi
 
-
-if [ -n "$SHOW_MODULE_HELP" ]; then
-    print_help
-else
-    if [ -z "$CHROOTDIR" ]; then
-        echo "ERROR: You must define the directory to build the chroot"
-        usage
-        exit 1
-    fi
-    #### Running template functions
-    test -n "$VERBOSE" && echo "Starting template functions"
-    for function in $FUNCTIONS; do
-        test -n "$VERBOSE" && echo "Running: $function"
-        $function || exit 1
-    done
+if [ -z "$CHROOTDIR" ]; then
+    echo "ERROR: You must define the directory to build the chroot"
+    usage
+    exit 1
 fi
+#### Running template functions
+test -n "$VERBOSE" && echo "Starting template functions"
+for function in $FUNCTIONS; do
+    test -n "$VERBOSE" && echo "Running: $function"
+    $function || exit 1
+done
 
 
 # vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
diff --git a/vnfs/libexec/wwmkchroot/functions b/vnfs/libexec/wwmkchroot/functions
--- a/vnfs/libexec/wwmkchroot/functions
+++ b/vnfs/libexec/wwmkchroot/functions
@@ -2,9 +2,10 @@
 
 eval `wwconfig -as`
 
-MEDIA_MOUNTPATH="/tmp/wwmkchroot.mount"
+MEDIA_MOUNTPATH="$CHROOTDIR/tmp/wwmkchroot.mount"
 
 export FUNCTIONS="sanity_check
+                  distro_check
                   init
                   prechroot
                   buildchroot
@@ -23,6 +24,16 @@ export FUNCTIONS="sanity_check
                   cleanup"
 
 
+set_as_overlay() {
+    FUNCTIONS="sanity_check
+               distro_check
+               init
+               set_overlay
+               buildchroot
+               configure_services
+               finalize
+               cleanup"
+}
 
 sanity_check() {
     if [ ! -x $WAREWULF_PREFIX/bin/cluster-env ]; then
@@ -31,6 +42,14 @@ sanity_check() {
     else
         $WAREWULF_PREFIX/bin/cluster-env;
     fi
+    if [ -z "$PKGLIST" ]; then
+        echo "ERROR: You must define the \$PKGLIST variable in the template!"
+        return 1
+    fi
+    return 0
+}
+
+distro_check() {
     return 0
 }
 
@@ -41,7 +60,6 @@ init() {
             exit 1
         fi
     fi
-
     if [ -n "$INSTALL_ISO" ]; then
         count=0
         for i in `echo $INSTALL_ISO | sed -e 's/,/ /'`; do
@@ -62,7 +80,10 @@ init() {
             fi
         done
     fi
+    return 0
+}
 
+set_overlay() {
     return 0
 }
 
@@ -71,8 +92,13 @@ prechroot() {
 }
 
 buildchroot() {
-    echo "The template you are using, doesn't have buildchroot() defined!"
-    return 1
+    $PKGR_CMD
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Failed to install packages"
+        cleanup
+        return 1
+    fi
+    return 0   
 }
 
 postchroot() {
@@ -173,6 +199,7 @@ configure_runlevel() {
     if [ -f "$CHROOTDIR/etc/inittab" ]; then
         sed -i -e 's@id:.:initdefault:@id:3:initdefault:@' $CHROOTDIR/etc/inittab
     fi
+    return 0
 }
 
 configure_timezone() {
@@ -182,6 +209,7 @@ configure_timezone() {
     if [ -f "/etc/adjtime" ]; then
         cp -a /etc/adjtime $CHROOTDIR/etc/adjtime
     fi
+    return 0
 }
 
 configure_ntp() {
@@ -200,10 +228,9 @@ configure_ntp() {
 
             echo "server $IPADDR prefer" >> $CHROOTDIR/etc/ntp.conf
             echo "restrict $IPADDR mask 255.255.255.255 nomodify notrap noquery" >> $CHROOTDIR/etc/ntp.conf
-
         fi
     fi
-
+    return 0
 }
 
 configure_services() {
@@ -220,20 +247,12 @@ cleanup() {
             fi
         done
     fi
-
     return 0
 }
 
 finalize() {
     return 0
 }
-
-
-# Default print_help function incase the module does not offer one
-print_help() {
-    echo "This module does not contain any additional help information"
-}
-
 
 
 # vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
diff --git a/vnfs/libexec/wwmkchroot/include-deb b/vnfs/libexec/wwmkchroot/include-deb
--- a/vnfs/libexec/wwmkchroot/include-deb
+++ b/vnfs/libexec/wwmkchroot/include-deb
@@ -1,23 +1,39 @@
 
-COMPONENTS=""
-REPO_NAME="os-base"
-DEB_CONF="/root/apt-ww.conf"
-DEB_CONF_FULL="$CHROOTDIR/root/apt-ww.conf"
-DEB_SRC="/root/apt/sources.list"
-DEB_SRC_FULL="$CHROOTDIR/root/apt/sources.list"
+APT_CONF="root/ww-apt.conf"
+DEB_SRCS="root/sources.list"
+DEB_ISOS="root/iso.list"
+APT_CMD="apt-get -c $CHROOTDIR/$APT_CONF -o Dir::Etc::SourceList=/$CHROOTDIR/"
 
-sanity_check() {
-    if [ ! -x $WAREWULF_PREFIX/bin/cluster-env ]; then
-        echo "warewulf-cluster package is recommended on nodes you are building VNFS images on.";
-        sleep 2;
-    else
-        $WAREWULF_PREFIX/bin/cluster-env;
+distro_check() {
+    if ! [ -x "/usr/bin/dpkg" ] ; then
+        echo "ERROR: Could not locate dpkg"
+        return 1
     fi
-
-    if ! dpkg -s debootstrap >/dev/null 2>&1; then
+    if ! dpkg -s debootstrap 2>&1 | grep Status | grep -v deinstall > /dev/null; then
         echo "ERROR: Could not query dpkg for debootstrap"
         return 1
     fi
+    return 0
+}
+
+set_overlay() {
+    if [ ! -d "$CHROOTDIR" -o ! -x "$CHROOTDIR/sbin/init" ]; then
+        echo "ERROR: This is an overlay that must work on an existing chroot!"
+        return 1
+    fi
+    if [ ! -f "$CHROOTDIR/etc/os-release" ]; then
+        echo "ERROR: This must be a Debian compatible chroot!"
+        return 1
+    fi
+    if [ -z "$INSTALL_ISO" ]; then
+        SOURCESPATH="$DEB_SRCS"
+    else
+        SOURCESPATH="$DEB_ISOS"
+    fi
+
+    APT_CMD="${APT_CMD}${SOURCESPATH}"
+    $APT_CMD update
+    PKGR_CMD="$APT_CMD install $PKGLIST"
     return 0
 }
 
@@ -29,143 +45,75 @@ configure_pam() {
 }
 
 prechroot() {
-
-    if [ -n "$OS_MIRROR" ]; then
-        DEB_MIRROR="$OS_MIRROR"
-    fi
-
     if [ -z "$DEB_MIRROR" ]; then
         echo "ERROR: You must define the \$DEB_MIRROR variable in the template"
         cleanup
-        exit 1
-    fi
-
-    if [ -z $SUITE ]; then
-        export SUITE="squeeze";
-    fi
-    if [ -z $ARCH ]; then
-        export ARCH="amd64";
-    fi
-    if [ -z $COMPONENTS ]; then
-        COMPONENTS="main,contrib,non-free";
-    fi
-
-    mkdir -p $CHROOTDIR
-    mkdir -p $CHROOTDIR/etc
-
-    cp -rap /etc/apt $CHROOTDIR/etc
-
-    DEB_CONF_DIRNAME=`dirname $DEB_CONF`
-    mkdir -m 0755 -p $CHROOTDIR/$DEB_CONF_DIRNAME
-
-    DEB_SRC_DIRNAME=`dirname $DEB_SRC`
-    mkdir -m 0755 -p $CHROOTDIR/$DEB_SRC_DIRNAME
-
-    > $CHROOTDIR/$DEB_CONF
-    > $CHROOTDIR/$DEB_SRC
-
-    echo '# Generated by wwmkchroot' >> $CHROOTDIR/$DEB_CONF
-    echo 'Dir "/" {' >> $CHROOTDIR/$DEB_CONF
-    echo '  Etc "root/apt/" {' >> $CHROOTDIR/$DEB_CONF
-    echo '    SourcesList "sources.list"' >> $CHROOTDIR/$DEB_CONF
-    echo '  }' >> $CHROOTDIR/$DEB_CONF
-    echo '}' >> $CHROOTDIR/$DEB_CONF
-    echo "" >> $CHROOTDIR/$DEB_CONF
-    echo 'DPkg {' >> $CHROOTDIR/$DEB_CONF
-    echo "  Chroot-Directory \"$CHROOTDIR\"" >> $CHROOTDIR/$DEB_CONF
-    echo '}' >> $CHROOTDIR/$DEB_CONF
-    echo "" >> $CHROOTDIR/$DEB_CONF
-
-    if [ -z "$INSTALL_ISO" ]; then
-        echo "deb $DEB_MIRROR $SUITE main contrib non-free" >> $CHROOTDIR/$DEB_SRC
-        echo "deb-src $DEB_MIRROR $SUITE main contrib non-free" >> $CHROOTDIR/$DEB_SRC
-        echo ""
-        echo "# For updates" >> $CHROOT/$DEB_SRC
-        echo "deb http://security.debian.org/ ${SUITE}/updates main contrib" >> $CHROOTDIR/$DEB_SRC
-        echo "deb-src http://security.debian.org/ ${SUITE}/updates main contrib" >> $CHROOTDIR/$DEB_SRC
-        echo "" >> $CHROOTDIR/$DEB_SRC
-    else
-        for i in `ls -d $MEDIA_MOUNTPATH.*`; do
-            if [ -z "$INSTALLDIRS" ]; then
-                INSTALLDIRS="file://$i"
-            else
-                INSTALLDIRS="$INSTALLDIRS,file://$i"
-            fi
-        done
-        echo "[$REPO_NAME]" >> $CHROOTDIR/$DEB_CONF
-        echo 'name=Linux $releasever - $basearch' >> $CHROOTDIR/$DEB_CONF
-        echo "baseurl=$INSTALLDIRS" >> $CHROOTDIR/$DEB_CONF
-        echo "enabled=1" >> $CHROOTDIR/$DEB_CONF
-        echo "gpgcheck=0" >> $CHROOTDIR/$DEB_CONF
-    fi
-
-    return 0;
-}
-
-buildchroot() {
-
-    if [ -z "$PKGLIST" ]; then
-        echo "ERROR: You must define the \$PKGLIST variable in the template!"
-        cleanup
-        exit 1
-    fi
-
-    debootstrap --arch=$ARCH --components=$COMPONENTS --variant=minbase \
-        --include=$PKGLIST \
-        $SUITE $CHROOTDIR $DEB_MIRROR
-
-    if [ $? -ne 0 ]; then
-        echo "ERROR: Failed to create chroot"
         return 1
     fi
+    if [ -z "$SUITE" ]; then
+        SUITE="jessie"
+    fi
+    if [ -z "$ARCH" ]; then
+        ARCH="i386"
+    fi
 
+    mkdir -p $CHROOTDIR/etc
+    cp -rap /etc/apt $CHROOTDIR/etc
+
+    DEB_SRCS_DIRNAME=`dirname $DEB_SRCS`
+    mkdir -m 0755 -p $CHROOTDIR/$DEB_SRCS_DIRNAME
+
+    > $CHROOTDIR/$APT_CONF
+    echo "APT{ Get{ Assume-Yes \"true\";" >> $CHROOTDIR/$APT_CONF
+    echo "AllowUnauthenticated \"true\"; }; };" >> $CHROOTDIR/$APT_CONF
+    echo "Dir \"$CHROOTDIR/\" { State "var/lib/apt/"" >> $CHROOTDIR/$APT_CONF
+    echo "{ status \"$CHROOTDIR/var/lib/dpkg/status\"; }; };" >> $CHROOTDIR/$APT_CONF
+    echo "DPkg{ Chroot-Directory \"$CHROOTDIR/\"; };" >> $CHROOTDIR/$APT_CONF
+
+    > $CHROOTDIR/$DEB_SRCS
+    echo "deb $DEB_MIRROR $SUITE main contrib non-free" >> $CHROOTDIR/$DEB_SRCS
+    echo "deb-src $DEB_MIRROR $SUITE main contrib non-free" >> $CHROOTDIR/$DEB_SRCS
+    echo "deb http://security.debian.org/ ${SUITE}/updates main contrib" >> $CHROOTDIR/$DEB_SRCS
+    echo "deb-src http://security.debian.org/ ${SUITE}/updates main contrib" >> $CHROOTDIR/$DEB_SRCS
+
+    if [ -z "$INSTALL_ISO" ]; then
+        SOURCESPATH="$DEB_SRCS"
+        PKGR_CMD="debootstrap --arch=$ARCH --variant=minbase $SUITE $CHROOTDIR $DEB_MIRROR"
+    else
+        SOURCESPATH="$DEB_ISOS"
+        > $CHROOTDIR/$SOURCESPATH
+        for i in `ls -d $MEDIA_MOUNTPATH.*`; do
+            if [ -z "$INSTALLISOS" ]; then
+                INSTALLISOS="true"
+                DEB_MIRROR="file://$i"
+                echo "deb file:$i/ $SUITE main contrib" >> $CHROOTDIR/$SOURCESPATH
+            else
+                echo "deb file:$i/ $SUITE main contrib" >> $CHROOTDIR/$SOURCESPATH
+            fi
+        done
+        PKGR_CMD="debootstrap --no-check-gpg $SUITE $CHROOTDIR $DEB_MIRROR"
+    fi
     return 0
 }
 
 postchroot() {
+    # copy a more robust sources.list to our chroot
+    cp $CHROOTDIR/$DEB_SRCS $CHROOTDIR/etc/apt/
+
+    # debootstrap created our base chroot and now
+    # we install all the required packages into it
+    APT_CMD="${APT_CMD}${SOURCESPATH}"
+    $APT_CMD update
+    $APT_CMD install $PKGLIST
+
     touch $CHROOTDIR/fastboot
     return 0
 }
 
-print_help () {
-cat <<'EOF'
-
-    Debian chroot recipe file options:
-
-    Debian Mirrors:
-        DEB_MIRROR="http://ftp.us.debian.org/debian/"
-        DEB_MIRROR="http://http.us.debian.org/debian/"
-
-    Valid architectures are:
-        ARCH="i386"
-        ARCH="amd64"
-
-    To date these are the current releases.
-    Future releases should also be supported.
-
-    Release code names:
-        SUITE="lenny"
-        SUITE="squeeze"
-        SUITE="wheezy"
-        SUITE="sid"
-
-    Standard components:
-        COMPONENTS="main,contrib,non-free"
-
-    Alternate package lists:
-    32 Bit:
-    PKGLIST="openssh-server,openssh-client,isc-dhcp-client, \
-                    pciutils,strace,nfs-common,ethtool,iproute, \
-                    iputils-ping,iputils-arping,net-tools,rsync, \
-                    firmware-bnx2, linux-image-686"
-
-    64 Bit:
-    PKGLIST="openssh-server,openssh-client,isc-dhcp-client, \
-                    pciutils,strace,nfs-common,ethtool,iproute, \
-                    iputils-ping,iputils-arping,net-tools,rsync, \
-                    firmware-bnx2, linux-image-amd64"
-
-EOF
+finalize() {
+    $APT_CMD clean
+    return 0
 }
+
 
 # vim: filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
diff --git a/vnfs/libexec/wwmkchroot/include-rhel b/vnfs/libexec/wwmkchroot/include-rhel
--- a/vnfs/libexec/wwmkchroot/include-rhel
+++ b/vnfs/libexec/wwmkchroot/include-rhel
@@ -1,34 +1,37 @@
 
-
 REPO_NAME="os-base"
 YUM_CONF="/root/yum-ww.conf"
 YUM_CMD="yum -c $CHROOTDIR/$YUM_CONF --tolerant --installroot $CHROOTDIR -y"
 
-sanity_check() {
-    if [ ! -x $WAREWULF_PREFIX/bin/cluster-env ]; then
-        echo "warewulf-cluster package is recommended on nodes you are building VNFS images on.";
-        sleep 2;
-    else
-        $WAREWULF_PREFIX/bin/cluster-env;
-    fi
-
-    if ! rpm -q yum >/dev/null 2>&1; then
+distro_check() {
+    if ! rpm -q yum >/dev/null 2>&1 ; then
         echo "ERROR: Could not query RPM for YUM"
         return 1
     fi
     return 0
 }
 
-prechroot() {
+set_overlay() {
+    if [ ! -d "$CHROOTDIR" -o ! -x "$CHROOTDIR/sbin/init" ]; then
+        echo "ERROR: This is an overlay that must work on an existing chroot!"
+        return 1
+    fi
+    if [ ! -f "$CHROOTDIR/etc/redhat-release" ]; then
+        echo "ERROR: This must be a Red Hat compatible chroot!"
+        return 1
+    fi
+    PKGR_CMD="$YUM_CMD install $PKGLIST"
+    return 0
+}
 
+prechroot() {
     if [ -n "$OS_MIRROR" ]; then
         YUM_MIRROR="$OS_MIRROR"
     fi
-
     if [[ -z "$YUM_MIRROR" && -z "$INSTALL_ISO" ]]; then
         echo "ERROR: You must define the \$YUM_MIRROR variable in the template"
         cleanup
-        exit 1
+        return 1
     fi
 
     VERSION=`rpm -qf /etc/redhat-release  --qf '%{VERSION}\n'`
@@ -43,7 +46,6 @@ prechroot() {
     mkdir -m 0755 -p $CHROOTDIR/$YUM_CONF_DIRNAME
 
     > $CHROOTDIR/$YUM_CONF
-
     echo "[main]" >> $CHROOTDIR/$YUM_CONF
     echo 'cachedir=/var/cache/yum/$basearch/$releasever' >> $CHROOTDIR/$YUM_CONF
     echo "keepcache=0" >> $CHROOTDIR/$YUM_CONF
@@ -84,37 +86,23 @@ prechroot() {
 
         YUM_MIRROR=$INSTALLDIRS
     fi
-
-}
-
-buildchroot() {
-
-    if [ -z "$PKGLIST" ]; then
-        echo "ERROR: You must define the \$PKGLIST variable in the template!"
-        cleanup
-        exit 1
-    fi
-
-    $YUM_CMD install $PKGLIST
-
-    if [ $? -ne 0 ]; then
-        echo "ERROR: Failed to create chroot"
-        return 1
-    fi
-
+    PKGR_CMD="$YUM_CMD install $PKGLIST"
     return 0
 }
 
 postchroot() {
     touch $CHROOTDIR/fastboot
-    if grep -q rename_device $CHROOTDIR/etc/sysconfig/network-scripts/network-functions; then
+
+    # we only want to add this kludge to the file once. lets make sure an
+    # improperly writen overlay template wont cause repeated file concatenation
+    if grep -q rename_device $CHROOTDIR/etc/sysconfig/network-scripts/network-functions && \
+       ! grep -q 'rename_device() { return 0; }' $CHROOTDIR/etc/sysconfig/network-scripts/network-functions; then
         echo "" >> $CHROOTDIR/etc/sysconfig/network-scripts/network-functions
         echo "# This is a kludge added by Warewulf so devices don't get renamed (broke things with IB)" >> $CHROOTDIR/etc/sysconfig/network-scripts/network-functions
         echo "rename_device() { return 0; }" >> $CHROOTDIR/etc/sysconfig/network-scripts/network-functions
     fi
     return 0
 }
-
 
 
 # vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
