made some new changes
git-svn-id: https://warewulf.lbl.gov/svn/trunk@1647 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/icr/libexec/wwinit/88-IntelIB.init b/icr/libexec/wwinit/88-IntelIB.init
--- a/icr/libexec/wwinit/88-IntelIB.init
+++ b/icr/libexec/wwinit/88-IntelIB.init
@@ -192,12 +192,12 @@ if [ $skip_master -ne 1 ]; then
     fi
 
     # Configure OFED Package
-    wwprint " + Configuring Intel IB OFED+ Package\n";
-    if ! config_pkg; then
-        wwprint "\nERROR: Failed to configure Intel IB OFED+ package" error;
-        reply_error;
-        exit 255;
-    fi
+#wwprint " + Configuring Intel IB OFED+ Package\n";
+# if ! config_pkg; then
+#     wwprint "\nERROR: Failed to configure Intel IB OFED+ package" error;
+#     reply_error;
+#     exit 255;
+# fi
 
     # Build IntelIB Package
     wwprint " note: These next steps may take a while...\n" yellow
